FROM ros:humble
SHELL ["/bin/bash", "-c"]
WORKDIR /quac

RUN apt update
RUN apt install -y ros-humble-rmw-cyclonedds-cpp

COPY ./quac_cmd_vel_mux /quac/src/quac_cmd_vel_mux
RUN . /opt/ros/humble/setup.bash && colcon build