TIMEOUT 30
DEFAULT Quac

MENU TITLE L4T boot options

LABEL primary
      MENU LABEL primary kernel
      LINUX /boot/Image
      INITRD /boot/initrd
      APPEND ${cbootargs} root=PARTUUID=442f94c7-d0bf-4c08-8fa3-66a0babab713 rw rootwait rootfstype=ext4 mminit_loglevel=4 console=ttyTCU0,115200 firmware_class.path=/etc/firmware fbcon=map:0 video=efifb:off console=tty0 efi=runtime pci=pcie_bus_perf nvme.use_threaded_interrupts=1 nv-auto-config 

LABEL Quac
      MENU LABEL Quac Configuration (UART DMA Fix + Custom Header Config: <CSI Camera IMX219 Dual>)
      LINUX /boot/Image
      FDT /boot/dtb/kernel_tegra234-p3768-0000+p3767-0005-nv-super.dtb
      OVERLAYS /boot/tegra234-p3767-camera-p3768-imx219-dual.dtbo,/boot/disable-uart1-dma.dtbo
      INITRD /boot/initrd
      APPEND ${cbootargs} root=PARTUUID=442f94c7-d0bf-4c08-8fa3-66a0babab713 rw rootwait rootfstype=ext4 mminit_loglevel=4 console=ttyTCU0,115200 firmware_class.path=/etc/firmware fbcon=map:0 video=efifb:off console=tty0 efi=runtime pci=pcie_bus_perf nvme.use_threaded_interrupts=1 nv-auto-config 