FROM ultralytics/ultralytics:latest-jetson-jetpack6

RUN apt-get update && apt-get install -y \
    unzip \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip

#RUN pip3 install opencv-python-headless numpy
RUN pip3 install onnxscript

WORKDIR /deepstream_tmp
# download DeepStream 7.1
RUN wget --content-disposition https://api.ngc.nvidia.com/v2/resources/nvidia/ngc-apps/ngc_cli/versions/4.15.0/files/ngccli_arm64.zip -O ngccli_arm64.zip
RUN unzip ngccli_arm64.zip
RUN chmod u+x ngc-cli/ngc
SHELL ["/bin/bash", "-c"]
# extract
RUN ./ngc-cli/ngc registry resource download-version "nvidia/deepstream:7.1"

WORKDIR /deepstream_tmp/deepstream_v7.1
RUN apt update
RUN apt install -y \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    libgstreamer-plugins-good1.0-dev \
    libgstreamer-plugins-bad1.0-dev \
    libgstrtspserver-1.0-dev \
    libyaml-cpp-dev \
    libssl-dev \
    wget \
    build-essential \
    pkg-config

RUN dpkg -i deepstream-7.1_7.1.0-1_arm64.deb
RUN apt install -f

WORKDIR /workspace
RUN apt update && apt-get install -y \
    build-essential cmake git pkg-config \
    libgl1-mesa-dev libx11-dev libxrandr-dev libxinerama-dev \
    libxcursor-dev libxi-dev libudev-dev libv4l-dev \
    libusb-1.0-0-dev libssl-dev freeglut3-dev mesa-utils mesa-common-dev

RUN git clone https://github.com/realsenseai/librealsense.git
WORKDIR /workspace/librealsense/build
RUN cmake ..
RUN cmake --build . --config Release
RUN cmake --install .

# --- ros2 jazzy ---

WORKDIR /workspace/ros2_jazzy/src
WORKDIR /workspace/ros2_jazzy

RUN apt update && apt install locales
RUN locale-gen en_US en_US.UTF-8
RUN update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
RUN LANG=en_US.UTF-8

RUN apt install software-properties-common -y
RUN add-apt-repository universe

RUN apt update && apt install curl -y
RUN ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F'"' '{print $4}') && \
    curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo ${UBUNTU_CODENAME:-${VERSION_CODENAME}})_all.deb" && \
    dpkg -i /tmp/ros2-apt-source.deb

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y \
      python3-flake8-blind-except \
      python3-flake8-class-newline \
      python3-flake8-deprecated \
      python3-mypy \
      python3-pip \
      python3-pytest \
      python3-pytest-cov \
      python3-pytest-mock \
      python3-pytest-repeat \
      python3-pytest-rerunfailures \
      python3-pytest-runner \
      python3-pytest-timeout \
      ros-dev-tools

RUN vcs import --input https://raw.githubusercontent.com/ros2/ros2/jazzy/ros2.repos src
RUN apt upgrade -y
RUN rosdep init
RUN rosdep update
RUN rosdep install --from-paths src --ignore-src -y --skip-keys "fastcdr rti-connext-dds-6.0.1 urdfdom_headers"

RUN python3 -m pip install setuptools==79.0.1 wheel

RUN colcon build --symlink-install

# --- app ---

WORKDIR /workspace/ros2_ws

#COPY ./dependencies/DeepStream-Yolo /workspace/ros2_ws/src/quac/dependencies/DeepStream-Yolo
#COPY ./quac_video /workspace/ros2_ws/src/quac/quac_video

#RUN colcon build

#COPY ./entrypoint.sh /entrypoint.sh
#RUN chmod +x /entrypoint.sh

#CMD /entrypoint.sh