services:

  cam_streamer_front:
    image: ghcr.io/wggrobotic/quac-depthai-streamer:stable

  cam_streamer_gripper:
    image: ghcr.io/wggrobotic/quac-realsense-streamer:stable

  cam_streamer_back:
    image: ghcr.io/wggrobotic/quac-realsense-streamer:stable

  landolt_c_detection_server:
    image: ghcr.io/wggrobotic/quac-landolt-c-detection-server:stable

  qrcode_detection_server:
    image: ghcr.io/wggrobotic/quac-qrcode-detection-server:stable

  hazmat_detection_server:
    image: ghcr.io/wggrobotic/quac-yolo-detection-server:stable

  paintroller_detection_server:
    image: ghcr.io/wggrobotic/quac-yolo-detection-server:stable

  control:
    image: ghcr.io/wggrobotic/quac-control:stable

  ekf:
    image: ghcr.io/wggrobotic/quac-ekf:stable

  arm_target_controller:
    image: ghcr.io/wggrobotic/quac-arm-target-controller:stable

  inverse_kinematics:
    image: ghcr.io/wggrobotic/quac-inverse-kinematics:stable

  rsp:
    image: ghcr.io/wggrobotic/quac-rsp:stable

  cmd_vel_mux:
    image: ghcr.io/wggrobotic/quac-cmd-vel-mux:stable

  lidar:
    image: ghcr.io/wggrobotic/quac-lidar:stable

  sensors:
    image: ghcr.io/wggrobotic/quac-sensors:stable

  nav2:
    image: ghcr.io/wggrobotic/quac-nav2:stable

  slam_toolbox:
    image: ghcr.io/wggrobotic/quac-slam-toolbox:stable

  ohm_slam:
    image: ghcr.io/wggrobotic/quac-ohm-slam:stable
 
  rtabmap:
    image: ghcr.io/wggrobotic/quac-rtabmap:stable

  debug_shell:
    image: ghcr.io/wggrobotic/quac-debug-shell:stable