x-defaults: &defaults
  stop_signal: SIGINT
  network_mode: "host"
  volumes:
    - quac_trt_engines:/quac_trt_engines
    - ./src/quac:/quac/src/quac:ro
  environment:
    - DISABLE_WHEELS=${DISABLE_WHEELS}
    - DISABLE_ARM=${DISABLE_ARM}
    - DISABLE_THERMAL_CAM=${DISABLE_THERMAL_CAM}
    - DISABLE_IMU=${DISABLE_IMU}
    - DISABLE_MAGNETOMETER=${DISABLE_MAGNETOMETER}
    - NVIDIA_VISIBLE_DEVICES=all
    - QUAC_ENGINES_DIR=/quac_trt_engines/
    - SIM_MODE=${SIM_MODE}

volumes:
  quac_trt_engines:

services:

  camera_front:
    <<: *defaults
    runtime: nvidia
    ipc: host
    privileged: true
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac camera_app.launch.py camera_name:=camera_front"

  camera_back:
    <<: *defaults
    runtime: nvidia
    ipc: host
    privileged: true
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac camera_app.launch.py camera_name:=camera_back"

  control:
    <<: *defaults
    devices:
      - ${WHEELS_DEVICE}:${WHEELS_DEVICE}
      - ${ARM_DEVICE}:${ARM_DEVICE}
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac control.launch.py"

  inverse_kinematics:
    <<: *defaults
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac inverse_kinematics.launch.py sim_mode:=${SIM_MODE:-false}"

  rsp:
    <<: *defaults
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac rsp.launch.py disable_wheels:=${DISABLE_WHEELS:-false} disable_arm:=${DISABLE_ARM:-false} sim_mode:=${SIM_MODE:-false}"

  twist_mux:
    <<: *defaults
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac twist_mux.launch.py sim_mode:=${SIM_MODE:-false}"

  lidar:
    <<: *defaults
    devices:
      - /dev/quac/lidar_uart:/dev/quac/lidar_uart
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac lidar.launch.py"

  sensors:
    <<: *defaults
    privileged: true
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac sensors.launch.py disable_thermal_cam:=${DISABLE_THERMAL_CAM:-false} disable_imu:=${DISABLE_IMU:-false} disable_magnetometer:=${DISABLE_MAGNETOMETER:-false}"

  nav2:
    <<: *defaults
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac nav2.launch.py sim_mode:=${SIM_MODE:-false}"

  slam_toolbox:
    <<: *defaults
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac slam_toolbox.launch.py sim_mode:=${SIM_MODE:-false}"

  ohm_slam:
    <<: *defaults
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac ohm_slam.launch.py sim_mode:=${SIM_MODE:-false}"

  gazebo:
    <<: *defaults
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src/quac:/quac/src/quac:ro
    devices:
      - /dev/dri:/dev/dri
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac gazebo.launch.py"

  rviz:
    <<: *defaults
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src/quac:/quac/src/quac:ro
    devices:
      - /dev/dri:/dev/dri
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac rviz.launch.py"