services:

  camera_front:
    build:
      dockerfile: dockerfiles/camera.dockerfile
    image: quac_camera:dev

  camera_back:
    build:
      dockerfile: dockerfiles/camera.dockerfile
    image: quac_camera:dev

  control:
    build:
      dockerfile: dockerfiles/control.dockerfile
    image: quac_control:dev

  inverse_kinematics:
    build:
      dockerfile: dockerfiles/control.dockerfile
    image: quac_control:dev

  rsp:
    build:
      dockerfile: dockerfiles/rsp.dockerfile
    image: quac_rsp:dev

  twist_mux:
    build:
      dockerfile: dockerfiles/twist_mux.dockerfile
    image: quac_twist_mux:dev

  lidar:
    build:
      dockerfile: dockerfiles/lidar.dockerfile
    image: quac_lidar:dev

  sensors:
    build:
      dockerfile: dockerfiles/sensors.dockerfile
    image: quac_sensors:dev

  nav2:
    build:
      dockerfile: dockerfiles/nav2.dockerfile
    image: quac_nav2:dev

  slam_toolbox:
    build:
      dockerfile: dockerfiles/slam_toolbox.dockerfile
    image: quac_slam_toolbox:dev

  ohm_slam:
    build:
      dockerfile: dockerfiles/ohm_slam.dockerfile
    image: quac_ohm_slam:dev

  rtabmap:
    build:
      dockerfile: dockerfiles/rtabmap.dockerfile
    image: quac_rtabmap:dev

  gazebo:
    build:
      dockerfile: dockerfiles/gazebo.dockerfile
    image: quac_gazebo:dev

  rviz:
    build:
      dockerfile: dockerfiles/rviz.dockerfile
    image: quac_rviz:dev