defaults: &defaults
  stop_signal: SIGINT
  network_mode: "host"
  volumes:
    - quac_trt_engines:/quac_trt_engines
    - ../src/quac:/quac/src/quac:ro
  environment:
    - DISABLE_WHEELS=${DISABLE_WHEELS}
    - DISABLE_ARM=${DISABLE_ARM}
    - DISABLE_THERMAL_CAM=${DISABLE_THERMAL_CAM}
    - DISABLE_IMU=${DISABLE_IMU}
    - DISABLE_MAGNETOMETER=${DISABLE_MAGNETOMETER}
    - NVIDIA_VISIBLE_DEVICES=all
    - QUAC_ENGINES_DIR=/quac_trt_engines/
    - SIM_MODE=${SIM_MODE}

volumes:
  quac_trt_engines:

services:

  camera_front:
    <<: *defaults
    image: ghcr.io/wggrobotic/quac-camera:latest
    runtime: nvidia
    ipc: host
    privileged: true
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac camera_app.launch.py camera_name:=camera_front"

  camera_back:
    <<: *defaults
    image: ghcr.io/wggrobotic/quac-camera:latest
    runtime: nvidia
    ipc: host
    privileged: true
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac camera_app.launch.py camera_name:=camera_back"

  control:
    <<: *defaults
    image: ghcr.io/wggrobotic/quac-control:latest
    devices:
      - ${WHEELS_DEVICE}:${WHEELS_DEVICE}
      - ${ARM_DEVICE}:${ARM_DEVICE}
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac control.launch.py"

  inverse_kinematics:
    <<: *defaults
    image: ghcr.io/wggrobotic/quac-control:latest
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac inverse_kinematics.launch.py sim_mode:=${SIM_MODE}"

  rsp:
    <<: *defaults
    image: ghcr.io/wggrobotic/quac-rsp:latest
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac rsp.launch.py disable_wheels:=${DISABLE_WHEELS:-false} disable_arm:=${DISABLE_ARM:-false} sim_mode:=${SIM_MODE}"

  twist_mux:
    <<: *defaults
    image: ghcr.io/wggrobotic/quac-twist-mux:latest
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac twist_mux.launch.py sim_mode:=${SIM_MODE}"

  lidar:
    <<: *defaults
    image: ghcr.io/wggrobotic/quac-lidar:latest
    devices:
      - /dev/quac/lidar_uart:/dev/quac/lidar_uart
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac lidar.launch.py"

  sensors:
    <<: *defaults
    image: ghcr.io/wggrobotic/quac-sensors:latest
    privileged: true
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac sensors.launch.py disable_thermal_cam:=${DISABLE_THERMAL_CAM:-false} disable_imu:=${DISABLE_IMU:-false} disable_magnetometer:=${DISABLE_MAGNETOMETER:-false}"

  nav2:
    <<: *defaults
    image: ghcr.io/wggrobotic/quac-nav2:latest
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac nav2.launch.py sim_mode:=${SIM_MODE}"

  slam_toolbox:
    <<: *defaults
    image: ghcr.io/wggrobotic/quac-slam-toolbox:latest
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac slam_toolbox.launch.py sim_mode:=${SIM_MODE}"

  ohm_slam:
    <<: *defaults
    image: ghcr.io/wggrobotic/quac-ohm-slam:latest
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac ohm_slam.launch.py sim_mode:=${SIM_MODE}"

  gazebo:
    <<: *defaults
    image: ghcr.io/wggrobotic/quac-gazebo:latest
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac gazebo.launch.py"
