quac:
  video_app:
    ros__parameters:
      multicast: true
      ip: "192.168.137.26"
      #ip: "192.168.1.136"

      front:
        port: 5000
        cam_serial: "827312072798"
      back:
        port: 5001
        cam_serial: "938422071694" 