quac:
  video_app:
    ros__parameters:
      multicast: true
      ip: "192.168.137.26"
      #ip: "192.168.1.136"

      width: 640
      height: 480
      fps: 30
      
      front:
        port: 5000
        serial_number: "827312072798"
      back:
        port: 5001
        serial_number: "938422071694" 

      