services:
  quac:
    image: quac:dev
    entrypoint: ["/entrypoint.sh"]
    stop_signal: SIGINT

    build:
      context: .
      dockerfile: quac/dockerfile
    
    network_mode: "host"
    stdin_open: true
    tty: true
    init: true
    
    environment:
      DISABLE_WHEELS: false
      DISABLE_LIDAR: false
      DISABLE_ARM: false
    devices: []

  quac_video:
    image: quac_video:dev
    #entrypoint: ["/entrypoint.video.sh"]

    build:
      context: .
      dockerfile: dockerfile.video
    
    network_mode: "host"
    runtime: nvidia
    ipc: host
    stdin_open: true
    tty: true
    init: true
    privileged: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    devices: []
    volumes:
      - quac_video_trt_engines:/workspace/ros2_ws/engines

volumes:
  quac_video_trt_engines: