version: "3.9"

services:
  camera_front_app:
    image: quac_camera_app:dev
    build:
      context: ../
      dockerfile: docker/images/camera_app.dockerfile
    stop_signal: SIGINT
    network_mode: "host"
    runtime: nvidia
    ipc: host
    privileged: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - QUAC_ENGINES_DIR=/quac_trt_engines/
    volumes:
      - quac_trt_engines:/quac_trt_engines
      - ../src/quac:/quac/src/quac:ro
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac camera_app.launch.py camera_name:=camera_front"

  control:
    image: quac_control:dev
    build:
      context: ../
      dockerfile: docker/images/control.dockerfile
    stop_signal: SIGINT
    network_mode: "host"
    volumes:
      - ../src/quac:/quac/src/quac:ro
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac control.launch.py"

  rsp:
    image: quac_rsp:dev
    build:
      context: ../
      dockerfile: docker/images/rsp.dockerfile
    stop_signal: SIGINT
    network_mode: "host"
    volumes:
      - ../src/quac:/quac/src/quac:ro
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac rsp.launch.py disable_wheels:=true disable_arm:=true"

  lidar:
    image: quac_lidar:dev
    build:
      context: ../
      dockerfile: docker/images/lidar.dockerfile
    stop_signal: SIGINT
    network_mode: "host"
    volumes:
      - ../src/quac:/quac/src/quac:ro
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac lidar.launch.py"
    profiles:
      - hardware

  sensors:
    image: quac_sensors:dev
    build:
      context: ../
      dockerfile: docker/images/sensors.dockerfile
    stop_signal: SIGINT
    network_mode: "host"
    privileged: true
    volumes:
      - ../src/quac:/quac/src/quac:ro
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac sensors.launch.py"
    profiles:
      - hardware

  nav2:
    image: quac_nav2:dev
    build:
      context: ../
      dockerfile: docker/images/nav2.dockerfile
    stop_signal: SIGINT
    network_mode: "host"
    volumes:
      - ../src/quac:/quac/src/quac:ro
    command: /bin/bash -c ". /quac/src/quac/docker_setup.sh && ros2 launch quac nav2.launch.py"

volumes:
  quac_trt_engines: