quac:
  camera_front:
    camera_app:
      ros__parameters:
        width: 640
        height: 480
        fps: 30
        
        port: 5000
        serial_number: "827312072798"

  camera_back:
    camera_app:
      ros__parameters:
        width: 640
        height: 480
        fps: 30
        
        port: 5001
        serial_number: "938422071694"
        

      