quac:
  controller_manager:
    ros__parameters:
      update_rate: 10

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
        publish_rate: 10

      diff_drive_controller:
        type: diff_drive_controller/DiffDriveController
        publish_rate: 10

  diff_drive_controller:
    ros__parameters:
      left_wheel_names: ["wheel_front_left_joint", "wheel_rear_left_joint"]
      right_wheel_names: ["wheel_front_right_joint", "wheel_rear_right_joint"]
      wheel_separation: 0.47
      wheel_radius: 0.055
      cmd_vel_timeout: 0.5
      odom_frame_id: "odom"
      base_frame_id: "base_link"
      enable_odom_tf: true
      tf_frame_prefix_enable: false
