quac:
  camera_front:
    ros__parameters:
      capture:
        device_id: "19443010218B077E00"
        fps: 30
        color:
          width: 640
          height: 480
        depth:
          width: 640
          height: 480
      gst:
        port: 5000
        compression: "h264"
        h264:
          bitrate: 5000
          key_int_max: 60
      pointcloud:
        enable: false
        interval: 10
        frame: camera_front_depth_optical_frame
      image:
        enable: true
        interval: 5
        frame: camera_front_color_optical_frame
      imu:
        enable: true
        frame: camera_front_imu
        rate: 20
        
  camera_gripper:
    ros__parameters:
      capture:
        device_id: "827312072798"
        fps: 30
        color:
          width: 640
          height: 480
        depth:
          width: 640
          height: 480
      gst:
        port: 5002

        compression: "h264"
        h264:
          bitrate: 5000
          key_int_max: 60
      pointcloud:
        enable: true
        interval: 10
        frame: camera_gripper_depth_optical_frame
      image:
        enable: true
        interval: 2
        frame: camera_gripper_color_optical_frame
        
  camera_back:
    ros__parameters:
      capture:
        device_id: "938422071694"
        fps: 30
        color:
          width: 640
          height: 480
        depth:
          width: 640
          height: 480
      gst:
        port: 5001
        compression: "h264"
        h264:
          bitrate: 5000
          key_int_max: 60
      pointcloud:
        enable: true
        interval: 10
        frame: camera_back_depth_optical_frame
      image:
        enable: true
        interval: 2
        frame: camera_back_color_optical_frame