quac:
  camera_front:
    ros__parameters:
      width: 1920
      height: 1080
      fps: 30
      bitrate: 4000
      key_int_max: 10
      
      port: 5000
      serial_number: "827312072798"
      #serial_number: "938422071694"
      
      hazmat:
        enabled: true
        model: "hazmat_yolo26"
      paintroller:
        enabled: true
        model: "paintroller_yolo11"

  camera_back:
    ros__parameters:
      width: 1920
      height: 1080
      fps: 30
      bitrate: 4000
      key_int_max: 10
      
      port: 5001
      serial_number: "938422071694"

      hazmat:
        enabled: true
        model: "hazmat_yolo26"
      paintroller:
        enabled: true
        model: "paintroller_yolo11"
        

      