quac:
  camera_front:
    ros__parameters:
      width: 640
      height: 480
      fps: 30
      
      port: 5000
      serial_number: "827312072798"
      #serial_number: "938422071694"
      
      hazmat:
        enabled: true
        model: "hazmat_yolo26"
      paintroller:
        enabled: true
        model: "paintroller_yolo11"

      depth_detection:
        range: [0.3, 3.0]
        sample_diameter: 6
        min_sample: 20

  camera_back:
    ros__parameters:
      width: 640
      height: 480
      fps: 30
      
      port: 5001
      serial_number: "938422071694"

      hazmat:
        enabled: true
        model: "hazmat_yolo26"
      paintroller:
        enabled: true
        model: "paintroller_yolo11"
        

      