quac:
  cmd_vel_mux:
    ros__parameters:
      out:
        topic: cmd_vel
        stamped_flag: true
        stamp_frame: base_link
      in:
        topics: [cmd_vel_nav2, cmd_vel_pilot]
        timeouts: [0.5, 0.5]
        stamped_flags: [false, true]
        priorities: [10.0, 100.0]

