quac:
  controller_manager:
    ros__parameters:
      update_rate: 10

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
        publish_rate: 10

      diff_drive_controller:
        type: diff_drive_controller/DiffDriveController
        publish_rate: 10

      arm_position_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      wheel_monitor:
        type: quac_controllers/WheelMonitor

  diff_drive_controller:
    ros__parameters:
      left_wheel_names:
        - wheel_front_left_joint
        - wheel_rear_left_joint

      right_wheel_names: 
        - wheel_front_right_joint
        - wheel_rear_right_joint

      wheel_separation: 0.45
      wheel_radius: 0.055
      cmd_vel_timeout: 0.5
      odom_frame_id: "odom"
      base_frame_id: "base_link"
      enable_odom_tf: true
      tf_frame_prefix_enable: false
      use_stamped_vel: true

  arm_position_controller:
    ros__parameters:
      joints:
        - arm_servo_0_joint
        - arm_servo_1_joint
        - gripper_servo_joint

      command_interfaces:
        - position
        - velocity
      
      state_interfaces:
        - position
        - velocity
      
      state_publish_rate: 100.0
      action_monitor_rate: 50.0

      allow_partial_joints_goal: true
      open_loop_control: false
      allow_integration_in_goal_trajectories: true
      constraints:
        stopped_velocity_tolerance: 0.01
        goal_time: 0.0
  
  wheel_monitor:
    ros__parameters:
      wheel_names:
        - wheel_front_left_joint
        - wheel_rear_left_joint
        - wheel_front_right_joint
        - wheel_rear_right_joint