quac:
  hazmat_detection_server:
    ros__parameters:
      object_name: "hazmat_sign"
      camera_names: ["camera_gripper", "camera_back"]
      mapping: true
      publish_rate: 10
      publish_images_period: 10
      reference_frame: "map"
      consideration_radius: 20.0
      valid_distance_range: [0.00, 2.0]
      max_tf_stamp_difference: 0.5 
      detection_weight: 0.01
      confidence_threshold: 0.5
      min_times_detected: 10
      yolo_task: "detect"

  paintroller_detection_server:
    ros__parameters:
      object_name: "paintroller"
      camera_names: ["camera_gripper"]
      mapping: false # true
      publish_rate: 10
      publish_images_period: 10
      reference_frame: "map"
      consideration_radius: 0.05
      valid_distance_range: [0.08, 2.0]
      max_tf_stamp_difference: 0.5 
      detection_weight: 0.01
      confidence_threshold: 0.5
      min_times_detected: 10
      yolo_task: "obb"

  qrcode_detection_server:
    ros__parameters:
      object_name: "qrcode"
      camera_names: ["camera_gripper", "camera_back"]
      mapping: true
      publish_rate: 10
      publish_images_period: 10
      reference_frame: "map"  
      consideration_radius: 2.0
      valid_distance_range: [0.08, 2.0]
      max_tf_stamp_difference: 0.5 
      detection_weight: 0.01
      min_times_detected: 1

  landolt_c_detection_server:
    ros__parameters:
      object_name: "landolt_c"
      camera_names: ["camera_front", "camera_gripper"]
      mapping: true
      publish_rate: 10
      publish_images_period: 1
      reference_frame: "map"  
      consideration_radius: 2.0
      valid_distance_range: [0.08, 2.0]
      max_tf_stamp_difference: 0.5 
      detection_weight: 0.01
      min_times_detected: 1
      min_edge_count: 12
      min_ratio_circle: 0.8
      min_depth: 10
      requires_two: true
      color_threshold: 80
      enable_outer_default: false
      outer_default: "up"
      outer_up_configuration: 0.0

