quac:
  hazmat_detection_server:
    ros__parameters:
      topics: [camera_front/bgrd, camera_back/bgrd]

  qrcode_detection_server:
    ros__parameters:
      topics: [camera_front/bgrd, camera_back/bgrd]


      