FROM ros:jazzy

RUN sudo apt update && apt install git

RUN sudo apt install -y \
    ros-jazzy-ros2-control \
    ros-jazzy-ros2-controllers \
    ros-jazzy-xacro \
    ros-jazzy-rmw-cyclonedds-cpp

RUN rm -rf /var/lib/apt/lists/*

WORKDIR /ros2_ws
SHELL ["/bin/bash", "-c"]

COPY ./dependencies/rplidar_ros /ros2_ws/src/rplidar_ros

RUN . /opt/ros/jazzy/setup.bash && colcon build --packages-select rplidar_ros

COPY ./quac_control /ros2_ws/src/quac_control
RUN . /opt/ros/jazzy/setup.bash && colcon build

COPY ./quac /ros2_ws/src/quac
RUN . /opt/ros/jazzy/setup.bash && colcon build --packages-select quac

COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENV DISABLE_WHEELS=false
ENV DISABLE_LIDAR=false
ENV DISABLE_ARM=false

CMD /entrypoint.sh